/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VeriBiteFoodPredictor } from "./VeriBiteFoodPredictor";
export type { VeriBitePredictor } from "./VeriBitePredictor";
