/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VeriBiteFoodPredictor {
  export type FoodPredictionStruct = {
    id: BigNumberish;
    predictor: AddressLike;
    category: BigNumberish;
    shortText: string;
    ipfsCid: string;
    resultHash: BytesLike;
    stake: BigNumberish;
    outcome: BigNumberish;
    createdAt: BigNumberish;
  };

  export type FoodPredictionStructOutput = [
    id: bigint,
    predictor: string,
    category: bigint,
    shortText: string,
    ipfsCid: string,
    resultHash: string,
    stake: bigint,
    outcome: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    predictor: string;
    category: bigint;
    shortText: string;
    ipfsCid: string;
    resultHash: string;
    stake: bigint;
    outcome: bigint;
    createdAt: bigint;
  };
}

export interface VeriBiteFoodPredictorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchDistributeRewards"
      | "distributeReward"
      | "getContractStats"
      | "getPrediction"
      | "getPredictionIds"
      | "getPredictionIdsPaginated"
      | "getPredictionsByCategory"
      | "getPredictionsByOutcome"
      | "getUserPredictionIds"
      | "markOutcome"
      | "minStake"
      | "owner"
      | "pause"
      | "paused"
      | "platformFeeBps"
      | "predictionIds"
      | "predictions"
      | "renounceOwnership"
      | "submitFoodPrediction"
      | "totalPlatformFees"
      | "totalRewardsDistributed"
      | "totalStaked"
      | "transferOwnership"
      | "unpause"
      | "updateMinStake"
      | "updatePlatformFeeBps"
      | "userPredictionIds"
      | "userTotalRewards"
      | "userTotalStaked"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractWithdrawal"
      | "FoodPredictionSubmitted"
      | "MinStakeUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformFeeUpdated"
      | "PredictionOutcomeResolved"
      | "RewardPaid"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchDistributeRewards",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPrediction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionIdsPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionsByCategory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionsByOutcome",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPredictionIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markOutcome",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "minStake", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictionIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitFoodPrediction",
    values: [BigNumberish, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlatformFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateMinStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPredictionIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalStaked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchDistributeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionIdsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionsByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionsByOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPredictionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFoodPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlatformFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMinStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPredictionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ContractWithdrawalEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FoodPredictionSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    predictor: AddressLike,
    category: BigNumberish,
    resultHash: BytesLike,
    stake: BigNumberish,
    ipfsCid: string
  ];
  export type OutputTuple = [
    id: bigint,
    predictor: string,
    category: bigint,
    resultHash: string,
    stake: bigint,
    ipfsCid: string
  ];
  export interface OutputObject {
    id: bigint;
    predictor: string;
    category: bigint;
    resultHash: string;
    stake: bigint;
    ipfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinStakeUpdatedEvent {
  export type InputTuple = [newMinStake: BigNumberish];
  export type OutputTuple = [newMinStake: bigint];
  export interface OutputObject {
    newMinStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionOutcomeResolvedEvent {
  export type InputTuple = [id: BigNumberish, outcome: BigNumberish];
  export type OutputTuple = [id: bigint, outcome: bigint];
  export interface OutputObject {
    id: bigint;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardPaidEvent {
  export type InputTuple = [
    id: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, to: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeriBiteFoodPredictor extends BaseContract {
  connect(runner?: ContractRunner | null): VeriBiteFoodPredictor;
  waitForDeployment(): Promise<this>;

  interface: VeriBiteFoodPredictorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchDistributeRewards: TypedContractMethod<
    [ids: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  distributeReward: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getContractStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalPredictions: bigint;
        totalUsers: bigint;
        contractBalance: bigint;
        totalStake: bigint;
        totalRewards: bigint;
        totalFees: bigint;
      }
    ],
    "view"
  >;

  getPrediction: TypedContractMethod<
    [id: BigNumberish],
    [VeriBiteFoodPredictor.FoodPredictionStructOutput],
    "view"
  >;

  getPredictionIds: TypedContractMethod<[], [bigint[]], "view">;

  getPredictionIdsPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  getPredictionsByCategory: TypedContractMethod<
    [category: BigNumberish],
    [bigint[]],
    "view"
  >;

  getPredictionsByOutcome: TypedContractMethod<
    [outcome: BigNumberish],
    [bigint[]],
    "view"
  >;

  getUserPredictionIds: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  markOutcome: TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  minStake: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  predictionIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  predictions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        predictor: string;
        category: bigint;
        shortText: string;
        ipfsCid: string;
        resultHash: string;
        stake: bigint;
        outcome: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitFoodPrediction: TypedContractMethod<
    [
      category: BigNumberish,
      shortText: string,
      ipfsCid: string,
      resultHash: BytesLike
    ],
    [void],
    "payable"
  >;

  totalPlatformFees: TypedContractMethod<[], [bigint], "view">;

  totalRewardsDistributed: TypedContractMethod<[], [bigint], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateMinStake: TypedContractMethod<
    [_minStake: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePlatformFeeBps: TypedContractMethod<
    [_platformFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  userPredictionIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userTotalRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userTotalStaked: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchDistributeRewards"
  ): TypedContractMethod<[ids: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalPredictions: bigint;
        totalUsers: bigint;
        contractBalance: bigint;
        totalStake: bigint;
        totalRewards: bigint;
        totalFees: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrediction"
  ): TypedContractMethod<
    [id: BigNumberish],
    [VeriBiteFoodPredictor.FoodPredictionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPredictionIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPredictionIdsPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPredictionsByCategory"
  ): TypedContractMethod<[category: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPredictionsByOutcome"
  ): TypedContractMethod<[outcome: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserPredictionIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "markOutcome"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "predictionIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "predictions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        predictor: string;
        category: bigint;
        shortText: string;
        ipfsCid: string;
        resultHash: string;
        stake: bigint;
        outcome: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitFoodPrediction"
  ): TypedContractMethod<
    [
      category: BigNumberish,
      shortText: string,
      ipfsCid: string,
      resultHash: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalPlatformFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRewardsDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMinStake"
  ): TypedContractMethod<[_minStake: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformFeeBps"
  ): TypedContractMethod<[_platformFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPredictionIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTotalRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTotalStaked"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ContractWithdrawal"
  ): TypedContractEvent<
    ContractWithdrawalEvent.InputTuple,
    ContractWithdrawalEvent.OutputTuple,
    ContractWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "FoodPredictionSubmitted"
  ): TypedContractEvent<
    FoodPredictionSubmittedEvent.InputTuple,
    FoodPredictionSubmittedEvent.OutputTuple,
    FoodPredictionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "MinStakeUpdated"
  ): TypedContractEvent<
    MinStakeUpdatedEvent.InputTuple,
    MinStakeUpdatedEvent.OutputTuple,
    MinStakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionOutcomeResolved"
  ): TypedContractEvent<
    PredictionOutcomeResolvedEvent.InputTuple,
    PredictionOutcomeResolvedEvent.OutputTuple,
    PredictionOutcomeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RewardPaid"
  ): TypedContractEvent<
    RewardPaidEvent.InputTuple,
    RewardPaidEvent.OutputTuple,
    RewardPaidEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ContractWithdrawal(address,uint256)": TypedContractEvent<
      ContractWithdrawalEvent.InputTuple,
      ContractWithdrawalEvent.OutputTuple,
      ContractWithdrawalEvent.OutputObject
    >;
    ContractWithdrawal: TypedContractEvent<
      ContractWithdrawalEvent.InputTuple,
      ContractWithdrawalEvent.OutputTuple,
      ContractWithdrawalEvent.OutputObject
    >;

    "FoodPredictionSubmitted(uint256,address,uint8,bytes32,uint256,string)": TypedContractEvent<
      FoodPredictionSubmittedEvent.InputTuple,
      FoodPredictionSubmittedEvent.OutputTuple,
      FoodPredictionSubmittedEvent.OutputObject
    >;
    FoodPredictionSubmitted: TypedContractEvent<
      FoodPredictionSubmittedEvent.InputTuple,
      FoodPredictionSubmittedEvent.OutputTuple,
      FoodPredictionSubmittedEvent.OutputObject
    >;

    "MinStakeUpdated(uint256)": TypedContractEvent<
      MinStakeUpdatedEvent.InputTuple,
      MinStakeUpdatedEvent.OutputTuple,
      MinStakeUpdatedEvent.OutputObject
    >;
    MinStakeUpdated: TypedContractEvent<
      MinStakeUpdatedEvent.InputTuple,
      MinStakeUpdatedEvent.OutputTuple,
      MinStakeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "PredictionOutcomeResolved(uint256,uint8)": TypedContractEvent<
      PredictionOutcomeResolvedEvent.InputTuple,
      PredictionOutcomeResolvedEvent.OutputTuple,
      PredictionOutcomeResolvedEvent.OutputObject
    >;
    PredictionOutcomeResolved: TypedContractEvent<
      PredictionOutcomeResolvedEvent.InputTuple,
      PredictionOutcomeResolvedEvent.OutputTuple,
      PredictionOutcomeResolvedEvent.OutputObject
    >;

    "RewardPaid(uint256,address,uint256)": TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;
    RewardPaid: TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
