/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VeriBiteFoodPredictor__factory } from "./VeriBiteFoodPredictor__factory";
export { VeriBitePredictor__factory } from "./VeriBitePredictor__factory";
